name: flutter_application_gitgud
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  github: ^9.25.0
   
  flutter_web_auth_2: ^4.1.0
  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.5.3
  google_generative_ai: ^0.4.7
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_ui_auth: ^1.17.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - .env
  fonts:
    - family: Nunito
      fonts:
        - asset: font/nunito_italic.ttf
        - asset: font/nunito_regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"