final List<Map<String, String>> topics = [
  {'label': '3D', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ajax', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Algorithm', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Amp', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Android', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Angular', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ansible', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'API', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Arduino', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'ASP.NET', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Awesome Lists', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Amazon Web Services', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Azure', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Babel', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Bash', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Bitcoin', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Bootstrap', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Bot', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'C', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Chrome', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Chrome extension', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Command‑line interface', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Clojure', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Code quality', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Code review', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Compiler', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Continuous integration', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'C++', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Cryptocurrency', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Crystal', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'C#', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'CSS', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Data structures', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Data visualization', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Database', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Deep learning', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Dependency management', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Deployment', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Django', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Docker', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Documentation', 'icon': 'assets/icon/topic_icon.png'},
  {'label': '.NET', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Electron', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Elixir', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Emacs', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ember', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Emoji', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Emulator', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'ESLint', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ethereum', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Express', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Firebase', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Firefox', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Flask', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Font', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Framework', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Front end', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Game engine', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Git', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'GitHub API', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Go', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Google', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Gradle', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'GraphQL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Gulp', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Hacktoberfest', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Haskell', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Homebrew', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Homebridge', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'HTML', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'HTTP', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Icon font', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'iOS', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'IPFS', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Java', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'JavaScript', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Jekyll', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'jQuery', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'JSON', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Julia', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Jupyter Notebook', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Koa', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Kotlin', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Kubernetes', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Laravel', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'LaTeX', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Library', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Linux', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Localization (l10n)', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Lua', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Machine learning', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'macOS', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Markdown', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Mastodon', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Material Design', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'MATLAB', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Maven', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Minecraft', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Mobile', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Monero', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'MongoDB', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Mongoose', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Monitoring', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'MvvmCross', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'MySQL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'NativeScript', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Nim', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Natural language processing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Node.js', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'NoSQL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'npm', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Objective‑C', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'OpenGL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Operating system', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'P2P', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Package manager', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Parsing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Perl', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Phaser', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'PHP', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'PICO‑8', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Pixel Art', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'PostgreSQL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Project management', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Publishing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'PWA', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Python', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Qt', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'R', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Rails', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Raspberry Pi', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ratchet', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'React', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'React Native', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'ReactiveUI', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Redux', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'REST API', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ruby', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Rust', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Sass', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Scala', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'scikit‑learn', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Software‑defined networking', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Security', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Server', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Serverless', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Shell', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Sketch', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'SpaceVim', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Spring Boot', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'SQL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Storybook', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Support', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Swift', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Symfony', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Telegram', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'TensorFlow', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Terminal', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Terraform', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Testing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'X (Twitter)', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'TypeScript', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ubuntu', 'icon': 'assets/icon/topic_icon.png'},
];
