final List<Map<String, String>> topics = [
  {'label': '3D', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ajax', 'icon': 'assets/icon/ajax.png'},
  {'label': 'Algorithm', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Amp', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Android', 'icon': 'assets/icon/android.png'},
  {'label': 'Angular', 'icon': 'assets/icon/angular.png'},
  {'label': 'Ansible', 'icon': 'assets/icon/ansible.png'},
  {'label': 'API', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Arduino', 'icon': 'assets/icon/arduino.png'},
  {'label': 'ASP.NET', 'icon': 'assets/icon/aspnet.png'},
  {'label': 'Awesome Lists', 'icon': 'assets/icon/awesome.png'},
  {'label': 'Amazon Web Services', 'icon': 'assets/icon/aws.png'},
  {'label': 'Azure', 'icon': 'assets/icon/azure.png'},
  {'label': 'Babel', 'icon': 'assets/icon/babel.png'},
  {'label': 'Bash', 'icon': 'assets/icon/bash.png'},
  {'label': 'Bitcoin', 'icon': 'assets/icon/bitcoin.png'},
  {'label': 'Bootstrap', 'icon': 'assets/icon/bootstrap.png'},
  {'label': 'Bot', 'icon': 'assets/icon/bot.png'},
  {'label': 'C', 'icon': 'assets/icon/c.png'},
  {'label': 'Chrome', 'icon': 'assets/icon/chrome.png'},
  {'label': 'Chrome extension', 'icon': 'assets/icon/chrome-extension.png'},
  {'label': 'Command‑line interface', 'icon': 'assets/icon/cli.png'},
  {'label': 'Clojure', 'icon': 'assets/icon/clojure.png'},
  {'label': 'Code quality', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Code review', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Compiler', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Continuous integration', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'C++', 'icon': 'assets/icon/cpp.png'},
  {'label': 'Cryptocurrency', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Crystal', 'icon': 'assets/icon/crystal.png'},
  {'label': 'C#', 'icon': 'assets/icon/csharp.png'},
  {'label': 'CSS', 'icon': 'assets/icon/css.png'},
  {'label': 'Data structures', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Data visualization', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Database', 'icon': 'assets/icon/database.png'},
  {'label': 'Deep learning', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Dependency management', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Deployment', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Django', 'icon': 'assets/icon/django.png'},
  {'label': 'Docker', 'icon': 'assets/icon/docker.png'},
  {'label': 'Documentation', 'icon': 'assets/icon/topic_icon.png'},
  {'label': '.NET', 'icon': 'assets/icon/dotnet.png'},
  {'label': 'Electron', 'icon': 'assets/icon/electron.png'},
  {'label': 'Elixir', 'icon': 'assets/icon/elixir.png'},
  {'label': 'Emacs', 'icon': 'assets/icon/emacs.png'},
  {'label': 'Ember', 'icon': 'assets/icon/ember.png'},
  {'label': 'Emoji', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Emulator', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'ESLint', 'icon': 'assets/icon/eslint.png'},
  {'label': 'Ethereum', 'icon': 'assets/icon/ethereum.png'},
  {'label': 'Express', 'icon': 'assets/icon/express.png'},
  {'label': 'Firebase', 'icon': 'assets/icon/firebase.png'},
  {'label': 'Firefox', 'icon': 'assets/icon/firefox.png'},
  {'label': 'Flask', 'icon': 'assets/icon/flask.png'},
  {'label': 'Font', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Framework', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Front end', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Game engine', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Git', 'icon': 'assets/icon/git.png'},
  {'label': 'GitHub API', 'icon': 'assets/icon/github-api.png'},
  {'label': 'Go', 'icon': 'assets/icon/go.png'},
  {'label': 'Google', 'icon': 'assets/icon/google.png'},
  {'label': 'Gradle', 'icon': 'assets/icon/gradle.png'},
  {'label': 'GraphQL', 'icon': 'assets/icon/graphql.png'},
  {'label': 'Gulp', 'icon': 'assets/icon/gulp.png'},
  {'label': 'Hacktoberfest', 'icon': 'assets/icon/hacktoberfest.png'},
  {'label': 'Haskell', 'icon': 'assets/icon/haskell.png'},
  {'label': 'Homebrew', 'icon': 'assets/icon/homebrew.png'},
  {'label': 'Homebridge', 'icon': 'assets/icon/homebridge.png'},
  {'label': 'HTML', 'icon': 'assets/icon/html.png'},
  {'label': 'HTTP', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Icon font', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'iOS', 'icon': 'assets/icon/ios.png'},
  {'label': 'IPFS', 'icon': 'assets/icon/ipfs.png'},
  {'label': 'Java', 'icon': 'assets/icon/java.png'},
  {'label': 'JavaScript', 'icon': 'assets/icon/javascript.png'},
  {'label': 'Jekyll', 'icon': 'assets/icon/jekyll.png'},
  {'label': 'jQuery', 'icon': 'assets/icon/jquery.png'},
  {'label': 'JSON', 'icon': 'assets/icon/json.png'},
  {'label': 'Julia', 'icon': 'assets/icon/julia.png'},
  {'label': 'Jupyter Notebook', 'icon': 'assets/icon/jupyter-notebook.png'},
  {'label': 'Koa', 'icon': 'assets/icon/koa.png'},
  {'label': 'Kotlin', 'icon': 'assets/icon/kotlin.png'},
  {'label': 'Kubernetes', 'icon': 'assets/icon/kubernetes.png'},
  {'label': 'Laravel', 'icon': 'assets/icon/laravel.png'},
  {'label': 'LaTeX', 'icon': 'assets/icon/latex.png'},
  {'label': 'Library', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Linux', 'icon': 'assets/icon/linux.png'},
  {'label': 'Localization (l10n)', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Lua', 'icon': 'assets/icon/lua.png'},
  {'label': 'Machine learning', 'icon': 'assets/icon/machine-learning.png'},
  {'label': 'macOS', 'icon': 'assets/icon/macos.png'},
  {'label': 'Markdown', 'icon': 'assets/icon/markdown.png'},
  {'label': 'Mastodon', 'icon': 'assets/icon/mastodon.png'},
  {'label': 'Material Design', 'icon': 'assets/icon/material-design.png'},
  {'label': 'MATLAB', 'icon': 'assets/icon/matlab.png'},
  {'label': 'Maven', 'icon': 'assets/icon/maven.png'},
  {'label': 'Minecraft', 'icon': 'assets/icon/minecraft.png'},
  {'label': 'Mobile', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Monero', 'icon': 'assets/icon/monero.png'},
  {'label': 'MongoDB', 'icon': 'assets/icon/mongodb.png'},
  {'label': 'Mongoose', 'icon': 'assets/icon/mongoose.png'},
  {'label': 'Monitoring', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'MvvmCross', 'icon': 'assets/icon/mvvmcross.png'},
  {'label': 'MySQL', 'icon': 'assets/icon/mysql.png'},
  {'label': 'NativeScript', 'icon': 'assets/icon/nativescript.png'},
  {'label': 'Nim', 'icon': 'assets/icon/nim.png'},
  {'label': 'Natural language processing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Node.js', 'icon': 'assets/icon/nodejs.png'},
  {'label': 'NoSQL', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'npm', 'icon': 'assets/icon/npm.png'},
  {'label': 'Objective‑C', 'icon': 'assets/icon/objective-c.png'},
  {'label': 'OpenGL', 'icon': 'assets/icon/opengl.png'},
  {'label': 'Operating system', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'P2P', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Package manager', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Parsing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Perl', 'icon': 'assets/icon/perl.png'},
  {'label': 'Phaser', 'icon': 'assets/icon/phaser.png'},
  {'label': 'PHP', 'icon': 'assets/icon/php.png'},
  {'label': 'PICO‑8', 'icon': 'assets/icon/pico-8.png'},
  {'label': 'Pixel Art', 'icon': 'assets/icon/pixel-art.png'},
  {'label': 'PostgreSQL', 'icon': 'assets/icon/postgresql.png'},
  {'label': 'Project management', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Publishing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'PWA', 'icon': 'assets/icon/pwa.png'},
  {'label': 'Python', 'icon': 'assets/icon/python.png'},
  {'label': 'Qt', 'icon': 'assets/icon/qt.png'},
  {'label': 'R', 'icon': 'assets/icon/r.png'},
  {'label': 'Rails', 'icon': 'assets/icon/rails.png'},
  {'label': 'Raspberry Pi', 'icon': 'assets/icon/raspberry-pi.png'},
  {'label': 'Ratchet', 'icon': 'assets/icon/ratchet.png'},
  {'label': 'React', 'icon': 'assets/icon/react.png'},
  {'label': 'React Native', 'icon': 'assets/icon/react-native.png'},
  {'label': 'ReactiveUI', 'icon': 'assets/icon/reactiveui.png'},
  {'label': 'Redux', 'icon': 'assets/icon/redux.png'},
  {'label': 'REST API', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Ruby', 'icon': 'assets/icon/ruby.png'},
  {'label': 'Rust', 'icon': 'assets/icon/rust.png'},
  {'label': 'Sass', 'icon': 'assets/icon/sass.png'},
  {'label': 'Scala', 'icon': 'assets/icon/scala.png'},
  {'label': 'scikit‑learn', 'icon': 'assets/icon/scikit-learn.png'},
  {'label': 'Software‑defined networking', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Security', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Server', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Serverless', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Shell', 'icon': 'assets/icon/shell.png'},
  {'label': 'Sketch', 'icon': 'assets/icon/sketch.png'},
  {'label': 'SpaceVim', 'icon': 'assets/icon/spacevim.png'},
  {'label': 'Spring Boot', 'icon': 'assets/icon/spring-boot.png'},
  {'label': 'SQL', 'icon': 'assets/icon/sql.png'},
  {'label': 'Storybook', 'icon': 'assets/icon/storybook.png'},
  {'label': 'Support', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'Swift', 'icon': 'assets/icon/swift.png'},
  {'label': 'Symfony', 'icon': 'assets/icon/symfony.png'},
  {'label': 'Telegram', 'icon': 'assets/icon/telegram.png'},
  {'label': 'TensorFlow', 'icon': 'assets/icon/tensorflow.png'},
  {'label': 'Terminal', 'icon': 'assets/icon/terminal.png'},
  {'label': 'Terraform', 'icon': 'assets/icon/terraform.png'},
  {'label': 'Testing', 'icon': 'assets/icon/topic_icon.png'},
  {'label': 'X (Twitter)', 'icon': 'assets/icon/twitter.png'},
  {'label': 'TypeScript', 'icon': 'assets/icon/typescript.png'},
  {'label': 'Ubuntu', 'icon': 'assets/icon/ubuntu.png'},
];
