final List<Map<String, String>> topics = [
  {'label': '3D', 'icon': 'assets/icon/topic_icon.png', 'apiName': '3d'},
  {'label': 'Ajax', 'icon': 'assets/icon/ajax.png', 'apiName': 'ajax'},
  {'label': 'Algorithm', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'algorithm'},
  {'label': 'Amp', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'amp'},
  {'label': 'Android', 'icon': 'assets/icon/android.png', 'apiName': 'android'},
  {'label': 'Angular', 'icon': 'assets/icon/angular.png', 'apiName': 'angular'},
  {'label': 'Ansible', 'icon': 'assets/icon/ansible.png', 'apiName': 'ansible'},
  {'label': 'API', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'api'},
  {'label': 'Arduino', 'icon': 'assets/icon/arduino.png', 'apiName': 'arduino'},
  {'label': 'ASP.NET', 'icon': 'assets/icon/aspnet.png', 'apiName': 'asp-net'},
  {'label': 'Awesome Lists', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'awesome-lists'},
  {'label': 'Amazon Web Services', 'icon': 'assets/icon/aws.png', 'apiName': 'amazon-web-services'},
  {'label': 'Azure', 'icon': 'assets/icon/azure.png', 'apiName': 'azure'},
  {'label': 'Babel', 'icon': 'assets/icon/babel.png', 'apiName': 'babel'},
  {'label': 'Bash', 'icon': 'assets/icon/bash.png', 'apiName': 'bash'},
  {'label': 'Bitcoin', 'icon': 'assets/icon/bitcoin.png', 'apiName': 'bitcoin'},
  {'label': 'Bootstrap', 'icon': 'assets/icon/bootstrap.png', 'apiName': 'bootstrap'},
  {'label': 'Bot', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'bot'},
  {'label': 'C', 'icon': 'assets/icon/c.png', 'apiName': 'c'},
  {'label': 'Chrome', 'icon': 'assets/icon/chrome.png', 'apiName': 'chrome'},
  {'label': 'Chrome extension', 'icon': 'assets/icon/chrome-extension.png', 'apiName': 'chrome-extension'},
  {'label': 'Command‑line interface', 'icon': 'assets/icon/cli.png', 'apiName': 'command-line-interface'},
  {'label': 'Clojure', 'icon': 'assets/icon/clojure.png', 'apiName': 'clojure'},
  {'label': 'Code quality', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'code-quality'},
  {'label': 'Code review', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'code-review'},
  {'label': 'Compiler', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'compiler'},
  {'label': 'Continuous integration', 'icon': 'assets/icon/ci.png', 'apiName': 'continuous-integration'},
  {'label': 'C++', 'icon': 'assets/icon/cpp.png', 'apiName': 'c-plus-plus'},
  {'label': 'Cryptocurrency', 'icon': 'assets/icon/cryptocurrency.png', 'apiName': 'cryptocurrency'},
  {'label': 'Crystal', 'icon': 'assets/icon/crystal.png', 'apiName': 'crystal'},
  {'label': 'C#', 'icon': 'assets/icon/csharp.png', 'apiName': 'c-sharp'},
  {'label': 'CSS', 'icon': 'assets/icon/css.png', 'apiName': 'css'},
  {'label': 'Data structures', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'data-structures'},
  {'label': 'Data visualization', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'data-visualization'},
  {'label': 'Database', 'icon': 'assets/icon/database.png', 'apiName': 'database'},
  {'label': 'Deep learning', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'deep-learning'},
  {'label': 'Dependency management', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'dependency-management'},
  {'label': 'Deployment', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'deployment'},
  {'label': 'Django', 'icon': 'assets/icon/django.png', 'apiName': 'django'},
  {'label': 'Docker', 'icon': 'assets/icon/docker.png', 'apiName': 'docker'},
  {'label': 'Documentation', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'documentation'},
  {'label': '.NET', 'icon': 'assets/icon/dotnet.png', 'apiName': 'dotnet'},
  {'label': 'Electron', 'icon': 'assets/icon/electron.png', 'apiName': 'electron'},
  {'label': 'Elixir', 'icon': 'assets/icon/elixir.png', 'apiName': 'elixir'},
  {'label': 'Emacs', 'icon': 'assets/icon/emacs.png', 'apiName': 'emacs'},
  {'label': 'Ember', 'icon': 'assets/icon/ember.png', 'apiName': 'ember'},
  {'label': 'Emoji', 'icon': 'assets/icon/emoji.png', 'apiName': 'emoji'},
  {'label': 'Emulator', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'emulator'},
  {'label': 'ESLint', 'icon': 'assets/icon/eslint.png', 'apiName': 'eslint'},
  {'label': 'Ethereum', 'icon': 'assets/icon/ethereum.png', 'apiName': 'ethereum'},
  {'label': 'Express', 'icon': 'assets/icon/express.png', 'apiName': 'express'},
  {'label': 'Firebase', 'icon': 'assets/icon/firebase.png', 'apiName': 'firebase'},
  {'label': 'Firefox', 'icon': 'assets/icon/firefox.png', 'apiName': 'firefox'},
  {'label': 'Flask', 'icon': 'assets/icon/flask.png', 'apiName': 'flask'},
  {'label': 'Font', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'font'},
  {'label': 'Framework', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'framework'},
  {'label': 'Front end', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'front-end'},
  {'label': 'Game engine', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'game-engine'},
  {'label': 'Git', 'icon': 'assets/icon/git.png', 'apiName': 'git'},
  {'label': 'GitHub API', 'icon': 'assets/icon/github-api.png', 'apiName': 'github-api'},
  {'label': 'Go', 'icon': 'assets/icon/go.png', 'apiName': 'go'},
  {'label': 'Google', 'icon': 'assets/icon/google.png', 'apiName': 'google'},
  {'label': 'Gradle', 'icon': 'assets/icon/gradle.png', 'apiName': 'gradle'},
  {'label': 'GraphQL', 'icon': 'assets/icon/graphql.png', 'apiName': 'graphql'},
  {'label': 'Gulp', 'icon': 'assets/icon/gulp.png', 'apiName': 'gulp'},
  {'label': 'Hacktoberfest', 'icon': 'assets/icon/hacktoberfest.png', 'apiName': 'hacktoberfest'},
  {'label': 'Haskell', 'icon': 'assets/icon/haskell.png', 'apiName': 'haskell'},
  {'label': 'Homebrew', 'icon': 'assets/icon/homebrew.png', 'apiName': 'homebrew'},
  {'label': 'Homebridge', 'icon': 'assets/icon/homebridge.png', 'apiName': 'homebridge'},
  {'label': 'HTML', 'icon': 'assets/icon/html.png', 'apiName': 'html'},
  {'label': 'HTTP', 'icon': 'assets/icon/http.png', 'apiName': 'http'},
  {'label': 'Icon font', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'icon-font'},
  {'label': 'iOS', 'icon': 'assets/icon/ios.png', 'apiName': 'ios'},
  {'label': 'IPFS', 'icon': 'assets/icon/ipfs.png', 'apiName': 'ipfs'},
  {'label': 'Java', 'icon': 'assets/icon/java.png', 'apiName': 'java'},
  {'label': 'JavaScript', 'icon': 'assets/icon/javascript.png', 'apiName': 'javascript'},
  {'label': 'Jekyll', 'icon': 'assets/icon/jekyll.png', 'apiName': 'jekyll'},
  {'label': 'jQuery', 'icon': 'assets/icon/jquery.png', 'apiName': 'jquery'},
  {'label': 'JSON', 'icon': 'assets/icon/json.png', 'apiName': 'json'},
  {'label': 'Julia', 'icon': 'assets/icon/julia.png', 'apiName': 'julia'},
  {'label': 'Jupyter Notebook', 'icon': 'assets/icon/jupyter.png', 'apiName': 'jupyter-notebook'},
  {'label': 'Koa', 'icon': 'assets/icon/koa.png', 'apiName': 'koa'},
  {'label': 'Kotlin', 'icon': 'assets/icon/kotlin.png', 'apiName': 'kotlin'},
  {'label': 'Kubernetes', 'icon': 'assets/icon/kubernetes.png', 'apiName': 'kubernetes'},
  {'label': 'Laravel', 'icon': 'assets/icon/laravel.png', 'apiName': 'laravel'},
  {'label': 'LaTeX', 'icon': 'assets/icon/latex.png', 'apiName': 'latex'},
  {'label': 'Library', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'library'},
  {'label': 'Linux', 'icon': 'assets/icon/linux.png', 'apiName': 'linux'},
  {'label': 'Localization (l10n)', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'localization-l10n'},
  {'label': 'Lua', 'icon': 'assets/icon/lua.png', 'apiName': 'lua'},
  {'label': 'Machine learning', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'machine-learning'},
  {'label': 'macOS', 'icon': 'assets/icon/macos.png', 'apiName': 'macos'},
  {'label': 'Markdown', 'icon': 'assets/icon/markdown.png', 'apiName': 'markdown'},
  {'label': 'Mastodon', 'icon': 'assets/icon/mastodon.png', 'apiName': 'mastodon'},
  {'label': 'Material Design', 'icon': 'assets/icon/material-design.png', 'apiName': 'material-design'},
  {'label': 'MATLAB', 'icon': 'assets/icon/matlab.png', 'apiName': 'matlab'},
  {'label': 'Maven', 'icon': 'assets/icon/maven.png', 'apiName': 'maven'},
  {'label': 'Minecraft', 'icon': 'assets/icon/minecraft.png', 'apiName': 'minecraft'},
  {'label': 'Mobile', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'mobile'},
  {'label': 'Monero', 'icon': 'assets/icon/monero.png', 'apiName': 'monero'},
  {'label': 'MongoDB', 'icon': 'assets/icon/mongodb.png', 'apiName': 'mongodb'},
  {'label': 'Mongoose', 'icon': 'assets/icon/mongoose.png', 'apiName': 'mongoose'},
  {'label': 'Monitoring', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'monitoring'},
  {'label': 'MvvmCross', 'icon': 'assets/icon/mvvmcross.png', 'apiName': 'mvvmcross'},
  {'label': 'MySQL', 'icon': 'assets/icon/mysql.png', 'apiName': 'mysql'},
  {'label': 'NativeScript', 'icon': 'assets/icon/nativescript.png', 'apiName': 'nativescript'},
  {'label': 'Nim', 'icon': 'assets/icon/nim.png', 'apiName': 'nim'},
  {'label': 'Natural language processing', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'natural-language-processing'},
  {'label': 'Node.js', 'icon': 'assets/icon/nodejs.png', 'apiName': 'node-js'},
  {'label': 'NoSQL', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'nosql'},
  {'label': 'npm', 'icon': 'assets/icon/npm.png', 'apiName': 'npm'},
  {'label': 'Objective‑C', 'icon': 'assets/icon/objective-c.png', 'apiName': 'objective-c'},
  {'label': 'OpenGL', 'icon': 'assets/icon/opengl.png', 'apiName': 'opengl'},
  {'label': 'Operating system', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'operating-system'},
  {'label': 'P2P', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'p2p'},
  {'label': 'Package manager', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'package-manager'},
  {'label': 'Parsing', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'parsing'},
  {'label': 'Perl', 'icon': 'assets/icon/perl.png', 'apiName': 'perl'},
  {'label': 'Phaser', 'icon': 'assets/icon/phaser.png', 'apiName': 'phaser'},
  {'label': 'PHP', 'icon': 'assets/icon/php.png', 'apiName': 'php'},
  {'label': 'PICO‑8', 'icon': 'assets/icon/pico-8.png', 'apiName': 'pico-8'},
  {'label': 'Pixel Art', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'pixel-art'},
  {'label': 'PostgreSQL', 'icon': 'assets/icon/postgresql.png', 'apiName': 'postgresql'},
  {'label': 'Project management', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'project-management'},
  {'label': 'Publishing', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'publishing'},
  {'label': 'PWA', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'pwa'},
  {'label': 'Python', 'icon': 'assets/icon/python.png', 'apiName': 'python'},
  {'label': 'Qt', 'icon': 'assets/icon/qt.png', 'apiName': 'qt'},
  {'label': 'R', 'icon': 'assets/icon/r.png', 'apiName': 'r'},
  {'label': 'Rails', 'icon': 'assets/icon/rails.png', 'apiName': 'rails'},
  {'label': 'Raspberry Pi', 'icon': 'assets/icon/raspberry-pi.png', 'apiName': 'raspberry-pi'},
  {'label': 'Ratchet', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'ratchet'},
  {'label': 'React', 'icon': 'assets/icon/react.png', 'apiName': 'react'},
  {'label': 'React Native', 'icon': 'assets/icon/react-native.png', 'apiName': 'react-native'},
  {'label': 'ReactiveUI', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'reactiveui'},
  {'label': 'Redux', 'icon': 'assets/icon/redux.png', 'apiName': 'redux'},
  {'label': 'REST API', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'rest-api'},
  {'label': 'Ruby', 'icon': 'assets/icon/ruby.png', 'apiName': 'ruby'},
  {'label': 'Rust', 'icon': 'assets/icon/rust.png', 'apiName': 'rust'},
  {'label': 'Sass', 'icon': 'assets/icon/sass.png', 'apiName': 'sass'},
  {'label': 'Scala', 'icon': 'assets/icon/scala.png', 'apiName': 'scala'},
  {'label': 'scikit‑learn', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'scikit-learn'},
  {'label': 'Software‑defined networking', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'software-defined-networking'},
  {'label': 'Security', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'security'},
  {'label': 'Server', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'server'},
  {'label': 'Serverless', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'serverless'},
  {'label': 'Shell', 'icon': 'assets/icon/shell.png', 'apiName': 'shell'},
  {'label': 'Sketch', 'icon': 'assets/icon/sketch.png', 'apiName': 'sketch'},
  {'label': 'SpaceVim', 'icon': 'assets/icon/spacevim.png', 'apiName': 'spacevim'},
  {'label': 'Spring Boot', 'icon': 'assets/icon/spring-boot.png', 'apiName': 'spring-boot'},
  {'label': 'SQL', 'icon': 'assets/icon/sql.png', 'apiName': 'sql'},
  {'label': 'Storybook', 'icon': 'assets/icon/storybook.png', 'apiName': 'storybook'},
  {'label': 'Support', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'support'},
  {'label': 'Swift', 'icon': 'assets/icon/swift.png', 'apiName': 'swift'},
  {'label': 'Symfony', 'icon': 'assets/icon/symfony.png', 'apiName': 'symfony'},
  {'label': 'Telegram', 'icon': 'assets/icon/telegram.png', 'apiName': 'telegram'},
  {'label': 'TensorFlow', 'icon': 'assets/icon/tensorflow.png', 'apiName': 'tensorflow'},
  {'label': 'Terminal', 'icon': 'assets/icon/terminal.png', 'apiName': 'terminal'},
  {'label': 'Terraform', 'icon': 'assets/icon/terraform.png', 'apiName': 'terraform'},
  {'label': 'Testing', 'icon': 'assets/icon/topic_icon.png', 'apiName': 'testing'},
  {'label': 'X (Twitter)', 'icon': 'assets/icon/twitter.png', 'apiName': 'x-twitter'},
  {'label': 'TypeScript', 'icon': 'assets/icon/typescript.png', 'apiName': 'typescript'},
  {'label': 'Ubuntu', 'icon': 'assets/icon/ubuntu.png', 'apiName': 'ubuntu'},
];
